apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-log-verifier-tagged
data:
  elasticsearch-log-verifier-tagged: |
    monitoringProvider: ELASTICSEARCH
    accountName: ds-elastic
    index: kubernetes*
    filterKey: kubernetes.pod_name
    responseKeywords: log
    tags:
    - errorString: FATAL
      tag: FatalErrors
