apiVersion: v1
kind: Secret
metadata:
  name: opsmx-profile
type: Opaque
data:
  cdIntegration: dHJ1ZQ==
  sourceName: YXJnb2NkLWRzYXJnbw==
  opsmxIsdUrl: aHR0cHM6Ly9pc2QtZHNhcmdvLmRzLm9wc214Lm9yZw==
  user: YWRtaW4=
