apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmx-analysis                                            ## This AnalysisTemplate is used in rollout.yaml
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: opsmx-analysis-score                                  ## Match it with the above AnalysisTemplate name.
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-account        ## Match it with Service Account name
                containers:
                - name: opsmx-provider
                  image: 'quay.io/opsmxpublic/argo-isd-metric-provider-job:v1.1.9' 
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: metric-config-volume
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config     ## Match it with Provider ConfigMap Name 
                - name: metric-config-volume
                  projected:
                    sources:
                    - configMap:
                        name: metric-verifier       ## Match it with the Metric Template name
                    - configMap:
                        name: log-verifier          ## Match it with the Metric Template name
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile       ## Match it with the Kubernetes Secret name 
                    optional: false
